#
# NFProbe configuration file
#

#
# Adapters configuration
#
adapters:
  eth0: {
    description: 'Ethernet adapter',
    timeout_ms: 100
  }
  eth1: {
    description: 'Ethernet adapter',
    timeout_ms: 100
  }

#
# Logging formatters configuration
#
formatters:
  brief: {
    format: '%(message)s'
  }
  verbose: {
    format: '%(asctime)s %(name)-12s %(levelname)-8s %(message)s'
  }

#
# Logging handlers configuration
#
handlers:
  console: {
    class: logging.StreamHandler,
    formatter: verbose,
    level: DEBUG
  }

#
# Logging loggers configuration
#
root:
  handlers: [console]
  level: DEBUG