#
# NFProbe configuration file
#
#
# Adapters configuration
#
adapters:
  eth0: {
    description: 'Ethernet adapter',
    timeout_ms: 100
  }
  eth1: {
    description: 'Ethernet adapter',
    timeout_ms: 100
  }
#
# Loggers configuration
#
loggers:
  #
  # Version
  #
  version:
    1
  #
  # Logging formatters configuration
  #
  formatters:
    #
    # Brief formatter
    #
    brief: {
      format: '%(message)s'
    }
    #
    # Verbose formatter
    #
    verbose: {
      format: '%(asctime)s %(name)-12s %(levelname)-8s %(message)s'
    }
  #
  # Logging handlers configuration
  #
  handlers:
    #
    # Console handler
    #
    console: {
      class: logging.StreamHandler,
      formatter: verbose,
      level: DEBUG
    }
    #
    # Roatating file handler
    #
    rotatingfile: {
      class: logging.handlers.RotatingFileHandler,
      formatter: verbose,
      filename: nfprobe_rotating_file.log,
      maxBytes: 10000,
      backupCount: 3,
      level: DEBUG
    }
    #
    # File handler
    #
    file: {
      class: logging.FileHandler,
      formatter: verbose,
      filename: nfprobe_file.log,
      level: DEBUG
    }
  #
  # Logging loggers configuration
  #
  root:
    handlers: [console]
    level: DEBUG